source 'https://github.com/cppfw/cocoapods-repo.git'

project 'ruis-render-opengles/ruis-render-opengles.xcodeproj'

platform :ios, '13.0'

target "ruis-render-opengles" do
	pod 'ruis', '>= 0.5.199'
end
