source 'https://github.com/cppfw/cocoapods-repo.git'

project 'morda-opengles2-ren/morda-opengles2-ren.xcodeproj'

platform :ios, '8.0'

target "morda-opengles2-ren" do
	pod 'morda', '>= 0.5.163'
end
